default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: f1_data_development

test:
  <<: *default
  database: f1_data_test

production:
  primary: &primary_production
    <<: *default
    database: f1_data_production
    username: f1_data
    password: <%= ENV["F1_DATA_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: f1_data_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: f1_data_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: f1_data_production_cable
    migrations_paths: db/cable_migrate
